// Copyright 2016 - 2026 The excelize Authors. All rights reserved. Use of
// this source code is governed by a BSD-style license that can be found in
// the LICENSE file.
//
// Package excelize providing a set of functions that allow you to write to and
// read from XLAM / XLSM / XLSX / XLTM / XLTX files. Supports reading and
// writing spreadsheet documents generated by Microsoft Excel™ 2007 and later.
// Supports complex components by high compatibility, and provided streaming
// API for generating or reading data from a worksheet with huge amounts of
// data. This library needs Go version 1.25.0 or later.

package excelize

// autoFilterOperatorNames is the inverse of autoFilterOperators: comparison
// symbols back to the operator names stored in the file.
var autoFilterOperatorNames = map[string]string{
	"==": "equal",
	"!=": "notEqual",
	"<":  "lessThan",
	"<=": "lessThanOrEqual",
	">":  "greaterThan",
	">=": "greaterThanOrEqual",
}

// SetAutoFilterCriteria replaces the per-column criteria of an existing
// AutoFilter, using the same vocabulary GetAutoFilter returns. It complements
// AutoFilter, whose expression syntax can express at most two equality values
// per column and therefore cannot represent a checklist of arbitrary length —
// the common case for a value-picker filter.
//
// Call AutoFilter first to establish the range; this function only writes the
// criteria. Passing an empty slice clears all criteria while keeping the filter
// buttons. Columns whose ColID falls outside the filter range are rejected.
//
// For each column, Filters (an "show only these values" checklist, optionally
// including blanks) and CustomFilters (up to two operator/value comparisons
// joined by And) are mutually exclusive, matching the file format; when both
// are supplied, Filters wins.
func (f *File) SetAutoFilterCriteria(sheet string, columns []AutoFilterColumnCriteria) error {
	ws, err := f.workSheetReader(sheet)
	if err != nil {
		return err
	}
	ws.mu.Lock()
	defer ws.mu.Unlock()
	if ws.AutoFilter == nil {
		return ErrParameterInvalid
	}
	coordinates, err := rangeRefToCoordinates(ws.AutoFilter.Ref)
	if err != nil {
		return err
	}
	_ = sortCoordinates(coordinates)
	width := coordinates[2] - coordinates[0]
	var out []*xlsxFilterColumn
	for _, col := range columns {
		if col.ColID < 0 || col.ColID > width {
			name, _ := ColumnNumberToName(col.ColID + 1)
			return newInvalidAutoFilterColumnError(name)
		}
		fc := &xlsxFilterColumn{ColID: col.ColID}
		switch {
		case len(col.Filters) > 0 || col.Blank:
			filters := &xlsxFilters{Blank: col.Blank}
			for _, v := range col.Filters {
				filters.Filter = append(filters.Filter, &xlsxFilter{Val: v})
			}
			fc.Filters = filters
		case len(col.CustomFilters) > 0:
			custom := &xlsxCustomFilters{And: col.And}
			for i, c := range col.CustomFilters {
				if i == 2 {
					// The format allows at most two custom criteria per column.
					break
				}
				op := autoFilterOperatorNames[c.Operator]
				if op == "" {
					return newInvalidAutoFilterOperatorError(c.Operator, c.Value)
				}
				custom.CustomFilter = append(custom.CustomFilter, &xlsxCustomFilter{
					Operator: op,
					Val:      c.Value,
				})
			}
			fc.CustomFilters = custom
		default:
			// No criteria for this column — nothing to record.
			continue
		}
		out = append(out, fc)
	}
	ws.AutoFilter.FilterColumn = out
	return nil
}
