// Copyright 2016 - 2026 The excelize Authors. All rights reserved. Use of
// this source code is governed by a BSD-style license that can be found in
// the LICENSE file.
//
// Package excelize providing a set of functions that allow you to write to and
// read from XLAM / XLSM / XLSX / XLTM / XLTX files. Supports reading and
// writing spreadsheet documents generated by Microsoft Excel™ 2007 and later.
// Supports complex components by high compatibility, and provided streaming
// API for generating or reading data from a worksheet with huge amounts of
// data. This library needs Go version 1.25.0 or later.

package excelize

import "strings"

// autoFilterOperators maps the stored custom filter operator names onto the
// comparison symbols used by AutoFilter expressions, keeping read output in
// the same vocabulary as write input.
var autoFilterOperators = map[string]string{
	"equal":              "==",
	"notEqual":           "!=",
	"lessThan":           "<",
	"lessThanOrEqual":    "<=",
	"greaterThan":        ">",
	"greaterThanOrEqual": ">=",
}

// AutoFilterCustomCriteria is a single operator/value pair inside a custom
// AutoFilter (for example ">" and "2000").
type AutoFilterCustomCriteria struct {
	Operator string
	Value    string
}

// AutoFilterColumnCriteria describes the filter applied to one column of an
// AutoFilter range. ColID is the zero-based offset of the column from the
// first column of the AutoFilter range. Only one of Filters or CustomFilters
// is populated for a given column.
type AutoFilterColumnCriteria struct {
	ColID         int
	Filters       []string
	Blank         bool
	CustomFilters []AutoFilterCustomCriteria
	And           bool
}

// AutoFilterResult is the AutoFilter state read from a worksheet. Range is the
// filter range reference (for example "A1:C10"); Columns holds the per-column
// criteria, and is empty when the filter has buttons but no active criteria.
type AutoFilterResult struct {
	Range   string
	Columns []AutoFilterColumnCriteria
}

// GetAutoFilter provides a function to get the AutoFilter settings of a
// worksheet by a given worksheet name. The second return value reports whether
// the worksheet has an AutoFilter at all; when false the result is the zero
// value. This complements AutoFilter, which upstream excelize can write but
// not read back.
func (f *File) GetAutoFilter(sheet string) (AutoFilterResult, bool, error) {
	var result AutoFilterResult
	ws, err := f.workSheetReader(sheet)
	if err != nil {
		return result, false, err
	}
	ws.mu.Lock()
	defer ws.mu.Unlock()
	if ws.AutoFilter == nil {
		return result, false, nil
	}
	result.Range = strings.ReplaceAll(ws.AutoFilter.Ref, "$", "")
	for _, fc := range ws.AutoFilter.FilterColumn {
		if fc == nil {
			continue
		}
		col := AutoFilterColumnCriteria{ColID: fc.ColID}
		if fc.Filters != nil {
			col.Blank = fc.Filters.Blank
			for _, filter := range fc.Filters.Filter {
				if filter != nil {
					col.Filters = append(col.Filters, filter.Val)
				}
			}
		}
		if fc.CustomFilters != nil {
			col.And = fc.CustomFilters.And
			for _, cf := range fc.CustomFilters.CustomFilter {
				if cf == nil {
					continue
				}
				op := autoFilterOperators[cf.Operator]
				if op == "" {
					// An empty operator attribute defaults to equality in the
					// spec; preserve that as "==".
					op = "=="
				}
				col.CustomFilters = append(col.CustomFilters, AutoFilterCustomCriteria{
					Operator: op,
					Value:    cf.Val,
				})
			}
		}
		result.Columns = append(result.Columns, col)
	}
	return result, true, nil
}
