// Copyright 2016 - 2026 The excelize Authors. All rights reserved. Use of
// this source code is governed by a BSD-style license that can be found in
// the LICENSE file.
//
// Package excelize providing a set of functions that allow you to write to and
// read from XLAM / XLSM / XLSX / XLTM / XLTX files. Supports reading and
// writing spreadsheet documents generated by Microsoft Excel™ 2007 and later.
// Supports complex components by high compatibility, and provided streaming
// API for generating or reading data from a worksheet with huge amounts of
// data. This library needs Go version 1.25.0 or later.

package excelize

import (
	"bytes"
	"encoding/xml"
	"io"
	"path/filepath"
	"strings"
)

// The read-back structures below intentionally use plain, non-namespaced local
// names for every element and attribute. The chart parts on disk carry
// prefixes (c:, a:, r:); Go's XML decoder matches a struct field whose tag has
// no namespace URL against any element sharing that local name regardless of
// prefix, which lets a single set of structs decode charts written by excelize,
// Excel or any other producer.

// decodeChartAnchor is the drawing cell anchor that hosts a chart graphic
// frame. It is decoded from the raw inner XML captured by drawingParser.
type decodeChartAnchor struct {
	From         *decodeFrom                   `xml:"from"`
	To           *decodeTo                     `xml:"to"`
	Ext          *decodePositiveSize2D         `xml:"ext"`
	GraphicFrame decodeChartAnchorGraphicFrame `xml:"graphicFrame"`
}

type decodeChartAnchorGraphicFrame struct {
	Graphic decodeChartAnchorGraphic `xml:"graphic"`
}

type decodeChartAnchorGraphic struct {
	GraphicData decodeChartAnchorGraphicData `xml:"graphicData"`
}

type decodeChartAnchorGraphicData struct {
	Chart *decodeChartAnchorRef `xml:"chart"`
}

// decodeChartAnchorRef carries the r:id relationship reference to the chart
// part.
type decodeChartAnchorRef struct {
	RID string `xml:"id,attr"`
}

// decodeChartSpace is the root of a chart part (xl/charts/chartN.xml).
type decodeChartSpace struct {
	XMLName xml.Name        `xml:"chartSpace"`
	Chart   decodeChartData `xml:"chart"`
}

type decodeChartData struct {
	Title            *decodeChartTitle    `xml:"title"`
	AutoTitleDeleted *decodeChartAttrBool `xml:"autoTitleDeleted"`
	PlotArea         decodeChartPlotArea  `xml:"plotArea"`
	Legend           *decodeChartLegend   `xml:"legend"`
	PlotVisOnly      *decodeChartAttrBool `xml:"plotVisOnly"`
}

type decodeChartTitle struct {
	Tx decodeChartTx `xml:"tx"`
}

type decodeChartTx struct {
	StrRef *decodeChartStrRef `xml:"strRef"`
	Rich   *decodeChartRich   `xml:"rich"`
}

type decodeChartRich struct {
	P []decodeChartParagraph `xml:"p"`
}

type decodeChartParagraph struct {
	R []decodeChartRun `xml:"r"`
}

type decodeChartRun struct {
	T string `xml:"t"`
}

type decodeChartLegend struct {
	LegendPos *decodeChartAttrString `xml:"legendPos"`
}

type decodeChartPlotArea struct {
	AreaChart      []decodeChartPlot `xml:"areaChart"`
	Area3DChart    []decodeChartPlot `xml:"area3DChart"`
	BarChart       []decodeChartPlot `xml:"barChart"`
	Bar3DChart     []decodeChartPlot `xml:"bar3DChart"`
	BubbleChart    []decodeChartPlot `xml:"bubbleChart"`
	DoughnutChart  []decodeChartPlot `xml:"doughnutChart"`
	LineChart      []decodeChartPlot `xml:"lineChart"`
	Line3DChart    []decodeChartPlot `xml:"line3DChart"`
	PieChart       []decodeChartPlot `xml:"pieChart"`
	Pie3DChart     []decodeChartPlot `xml:"pie3DChart"`
	OfPieChart     []decodeChartPlot `xml:"ofPieChart"`
	RadarChart     []decodeChartPlot `xml:"radarChart"`
	ScatterChart   []decodeChartPlot `xml:"scatterChart"`
	StockChart     []decodeChartPlot `xml:"stockChart"`
	SurfaceChart   []decodeChartPlot `xml:"surfaceChart"`
	Surface3DChart []decodeChartPlot `xml:"surface3DChart"`
}

// decodeChartPlot is the shared shape of every c:*Chart plot element.
type decodeChartPlot struct {
	BarDir     *decodeChartAttrString `xml:"barDir"`
	Grouping   *decodeChartAttrString `xml:"grouping"`
	RadarStyle *decodeChartAttrString `xml:"radarStyle"`
	OfPieType  *decodeChartAttrString `xml:"ofPieType"`
	VaryColors *decodeChartAttrBool   `xml:"varyColors"`
	HoleSize   *decodeChartAttrInt    `xml:"holeSize"`
	GapWidth   *decodeChartAttrInt    `xml:"gapWidth"`
	Overlap    *decodeChartAttrInt    `xml:"overlap"`
	Ser        []decodeChartSer       `xml:"ser"`
}

type decodeChartSer struct {
	IDx        *decodeChartAttrInt  `xml:"idx"`
	Order      *decodeChartAttrInt  `xml:"order"`
	Tx         *decodeChartTx       `xml:"tx"`
	Cat        *decodeChartAxisData `xml:"cat"`
	Val        *decodeChartNumData  `xml:"val"`
	XVal       *decodeChartAxisData `xml:"xVal"`
	YVal       *decodeChartNumData  `xml:"yVal"`
	BubbleSize *decodeChartNumData  `xml:"bubbleSize"`
	Smooth     *decodeChartAttrBool `xml:"smooth"`
}

type decodeChartAxisData struct {
	StrRef *decodeChartStrRef `xml:"strRef"`
	NumRef *decodeChartNumRef `xml:"numRef"`
}

type decodeChartNumData struct {
	NumRef *decodeChartNumRef `xml:"numRef"`
}

type decodeChartStrRef struct {
	F        string               `xml:"f"`
	StrCache *decodeChartStrCache `xml:"strCache"`
}

type decodeChartStrCache struct {
	Pt []decodeChartPt `xml:"pt"`
}

type decodeChartNumRef struct {
	F        string               `xml:"f"`
	NumCache *decodeChartNumCache `xml:"numCache"`
}

type decodeChartNumCache struct {
	Pt []decodeChartPt `xml:"pt"`
}

type decodeChartPt struct {
	V string `xml:"v"`
}

type decodeChartAttrString struct {
	Val string `xml:"val,attr"`
}

type decodeChartAttrInt struct {
	Val int `xml:"val,attr"`
}

type decodeChartAttrBool struct {
	Val bool `xml:"val,attr"`
}

// GetCharts provides a function to get all charts in a worksheet by a given
// worksheet name. It returns the top-left anchor cell reference of every chart
// paired with its parsed definition; the two returned slices are parallel, so
// cells[i] anchors charts[i]. Combo charts (multiple plot types sharing one
// chart part) are returned as the first plot type encountered. This
// complements AddChart, which upstream excelize can write but not read back.
func (f *File) GetCharts(sheet string) ([]string, []*Chart, error) {
	f.mu.Lock()
	ws, err := f.workSheetReader(sheet)
	if err != nil {
		f.mu.Unlock()
		return nil, nil, err
	}
	f.mu.Unlock()
	if ws.Drawing == nil {
		return nil, nil, nil
	}
	target := f.getSheetRelationshipsTargetByID(sheet, ws.Drawing.RID)
	drawingXML := strings.TrimPrefix(strings.ReplaceAll(target, "..", "xl"), "/")
	drawingRels := strings.ReplaceAll(
		strings.ReplaceAll(drawingXML, "xl/drawings", "xl/drawings/_rels"), ".xml", ".xml.rels")
	return f.getCharts(sheet, drawingXML, drawingRels)
}

// GetChartCells returns all cell references that anchor a chart in a worksheet
// by a given worksheet name.
func (f *File) GetChartCells(sheet string) ([]string, error) {
	cells, _, err := f.GetCharts(sheet)
	return cells, err
}

// getCharts walks every cell anchor in a drawing part and extracts the charts.
func (f *File) getCharts(sheet, drawingXML, drawingRels string) (cells []string, charts []*Chart, err error) {
	var wsDr *xlsxWsDr
	if wsDr, _, err = f.drawingParser(drawingXML); err != nil {
		return
	}
	wsDr.mu.Lock()
	anchors := make([]*xdrCellAnchor, 0, len(wsDr.TwoCellAnchor)+len(wsDr.OneCellAnchor))
	anchors = append(anchors, wsDr.TwoCellAnchor...)
	anchors = append(anchors, wsDr.OneCellAnchor...)
	wsDr.mu.Unlock()
	for _, anchor := range anchors {
		cell, chart, ok := f.extractChart(sheet, anchor, drawingRels)
		if !ok {
			continue
		}
		cells = append(cells, cell)
		charts = append(charts, chart)
	}
	return
}

// extractChart resolves the chart part referenced by a cell anchor and parses
// it into a Chart. The boolean result reports whether the anchor hosts a chart
// (anchors carrying pictures or other objects are skipped).
func (f *File) extractChart(sheet string, anchor *xdrCellAnchor, drawingRels string) (string, *Chart, bool) {
	if anchor == nil {
		return "", nil, false
	}
	var a decodeChartAnchor
	// The stored inner XML is already namespace-transitional; decode it as-is.
	if err := f.xmlNewDecoder(strings.NewReader("<a>" + anchor.GraphicFrame + "</a>")).
		Decode(&a); err != nil && err != io.EOF {
		return "", nil, false
	}
	if a.GraphicFrame.Graphic.GraphicData.Chart == nil {
		return "", nil, false
	}
	rID := a.GraphicFrame.Graphic.GraphicData.Chart.RID
	if rID == "" || a.From == nil {
		return "", nil, false
	}
	rel := f.getDrawingRelationships(drawingRels, rID)
	if rel == nil {
		return "", nil, false
	}
	var chartPath string
	if strings.HasPrefix(rel.Target, "/") {
		chartPath = strings.TrimPrefix(rel.Target, "/")
	} else {
		chartPath = filepath.ToSlash(filepath.Clean("xl/drawings/" + rel.Target))
	}
	chartXML := f.readXML(chartPath)
	if len(chartXML) == 0 {
		return "", nil, false
	}
	var cs decodeChartSpace
	if err := f.xmlNewDecoder(bytes.NewReader(namespaceStrictToTransitional(chartXML))).
		Decode(&cs); err != nil && err != io.EOF {
		return "", nil, false
	}
	cell, err := CoordinatesToCellName(a.From.Col+1, a.From.Row+1)
	if err != nil {
		return "", nil, false
	}
	chart := f.buildChart(sheet, &cs, &a)
	return cell, chart, true
}

// buildChart maps a decoded chart part and its anchor onto the public Chart
// structure returned by GetCharts.
func (f *File) buildChart(sheet string, cs *decodeChartSpace, a *decodeChartAnchor) *Chart {
	chart := &Chart{Format: GraphicOptions{ScaleX: 1, ScaleY: 1}}
	plot, chartType := selectChartPlot(&cs.Chart.PlotArea)
	chart.Type = chartType
	if cs.Chart.Title != nil {
		chart.Title.Paragraph = []RichTextRun{{Text: chartTitleText(cs.Chart.Title)}}
	}
	if cs.Chart.Legend != nil && cs.Chart.Legend.LegendPos != nil {
		chart.Legend.Position = legendPositionName(cs.Chart.Legend.LegendPos.Val)
	}
	if plot != nil {
		if plot.HoleSize != nil {
			chart.HoleSize = plot.HoleSize.Val
		}
		if plot.GapWidth != nil {
			w := uint(plot.GapWidth.Val)
			chart.GapWidth = &w
		}
		if plot.Overlap != nil {
			o := plot.Overlap.Val
			chart.Overlap = &o
		}
		if plot.VaryColors != nil {
			v := plot.VaryColors.Val
			chart.VaryColors = &v
		}
		for _, ser := range plot.Ser {
			chart.Series = append(chart.Series, chartSeries(ser))
		}
	}
	f.applyChartAnchor(sheet, chart, a)
	return chart
}

// applyChartAnchor computes the chart pixel offset and dimension from its
// drawing cell anchor.
func (f *File) applyChartAnchor(sheet string, chart *Chart, a *decodeChartAnchor) {
	chart.Format.OffsetX = a.From.ColOff / EMU
	chart.Format.OffsetY = a.From.RowOff / EMU
	if a.To != nil {
		w := 0
		for col := a.From.Col; col < a.To.Col; col++ {
			w += f.getColWidth(sheet, col+1)
		}
		w = w - a.From.ColOff/EMU + a.To.ColOff/EMU
		h := 0
		for row := a.From.Row; row < a.To.Row; row++ {
			h += f.getRowHeight(sheet, row+1)
		}
		h = h - a.From.RowOff/EMU + a.To.RowOff/EMU
		if w > 0 {
			chart.Dimension.Width = uint(w)
		}
		if h > 0 {
			chart.Dimension.Height = uint(h)
		}
		return
	}
	if a.Ext != nil {
		chart.Dimension.Width = uint(a.Ext.Cx / EMU)
		chart.Dimension.Height = uint(a.Ext.Cy / EMU)
	}
}

// chartSeries maps one decoded series onto the public ChartSeries.
func chartSeries(ser decodeChartSer) ChartSeries {
	out := ChartSeries{}
	if ser.Tx != nil {
		out.Name = chartTxValue(ser.Tx)
	}
	switch {
	case ser.Cat != nil:
		out.Categories = axisDataRef(ser.Cat)
	case ser.XVal != nil:
		out.Categories = axisDataRef(ser.XVal)
	}
	switch {
	case ser.Val != nil && ser.Val.NumRef != nil:
		out.Values = ser.Val.NumRef.F
	case ser.YVal != nil && ser.YVal.NumRef != nil:
		out.Values = ser.YVal.NumRef.F
	}
	if ser.BubbleSize != nil && ser.BubbleSize.NumRef != nil {
		out.Sizes = ser.BubbleSize.NumRef.F
	}
	return out
}

// axisDataRef returns the formula reference of a category axis, preferring the
// string reference and falling back to a numeric reference.
func axisDataRef(d *decodeChartAxisData) string {
	if d.StrRef != nil {
		return d.StrRef.F
	}
	if d.NumRef != nil {
		return d.NumRef.F
	}
	return ""
}

// chartTxValue extracts a series-name reference or literal from a tx element.
func chartTxValue(tx *decodeChartTx) string {
	if tx.StrRef != nil {
		return tx.StrRef.F
	}
	if tx.Rich != nil {
		return richParagraphsText(tx.Rich.P)
	}
	return ""
}

// chartTitleText extracts the chart title, preferring rich literal text and
// falling back to a title formula reference.
func chartTitleText(t *decodeChartTitle) string {
	if t.Tx.Rich != nil {
		if s := richParagraphsText(t.Tx.Rich.P); s != "" {
			return s
		}
	}
	if t.Tx.StrRef != nil {
		if t.Tx.StrRef.StrCache != nil && len(t.Tx.StrRef.StrCache.Pt) > 0 {
			return t.Tx.StrRef.StrCache.Pt[0].V
		}
		return t.Tx.StrRef.F
	}
	return ""
}

// richParagraphsText concatenates the runs of rich-text paragraphs.
func richParagraphsText(ps []decodeChartParagraph) string {
	var b strings.Builder
	for _, p := range ps {
		for _, r := range p.R {
			b.WriteString(r.T)
		}
	}
	return b.String()
}

// selectChartPlot picks the first populated plot element from a plot area and
// maps it to a representative ChartType.
func selectChartPlot(pa *decodeChartPlotArea) (*decodeChartPlot, ChartType) {
	switch {
	case len(pa.BarChart) > 0:
		p := &pa.BarChart[0]
		return p, barColType(p, false)
	case len(pa.Bar3DChart) > 0:
		p := &pa.Bar3DChart[0]
		return p, barColType(p, true)
	case len(pa.LineChart) > 0:
		return &pa.LineChart[0], Line
	case len(pa.Line3DChart) > 0:
		return &pa.Line3DChart[0], Line3D
	case len(pa.PieChart) > 0:
		return &pa.PieChart[0], Pie
	case len(pa.Pie3DChart) > 0:
		return &pa.Pie3DChart[0], Pie3D
	case len(pa.DoughnutChart) > 0:
		return &pa.DoughnutChart[0], Doughnut
	case len(pa.AreaChart) > 0:
		p := &pa.AreaChart[0]
		return p, areaType(p, false)
	case len(pa.Area3DChart) > 0:
		p := &pa.Area3DChart[0]
		return p, areaType(p, true)
	case len(pa.ScatterChart) > 0:
		return &pa.ScatterChart[0], Scatter
	case len(pa.RadarChart) > 0:
		return &pa.RadarChart[0], Radar
	case len(pa.BubbleChart) > 0:
		return &pa.BubbleChart[0], Bubble
	case len(pa.OfPieChart) > 0:
		p := &pa.OfPieChart[0]
		if p.OfPieType != nil && p.OfPieType.Val == "bar" {
			return p, BarOfPie
		}
		return p, PieOfPie
	case len(pa.StockChart) > 0:
		return &pa.StockChart[0], StockHighLowClose
	case len(pa.Surface3DChart) > 0:
		return &pa.Surface3DChart[0], Surface3D
	case len(pa.SurfaceChart) > 0:
		return &pa.SurfaceChart[0], Contour
	}
	return nil, Col
}

// legendPositionName maps a stored legend position code (l/r/t/b/tr) back to
// the API word accepted by AddChart, keeping the round-trip symmetric.
func legendPositionName(code string) string {
	for name, c := range chartLegendPosition {
		if c == code {
			return name
		}
	}
	return code
}

// chartGrouping normalizes the grouping attribute of a plot element.
func chartGrouping(p *decodeChartPlot) string {
	if p.Grouping != nil {
		return p.Grouping.Val
	}
	return ""
}

// barColType resolves a bar/column plot to a ChartType from its direction and
// grouping. threeD selects the 3-D variants.
func barColType(p *decodeChartPlot, threeD bool) ChartType {
	col := p.BarDir == nil || p.BarDir.Val != "bar"
	switch chartGrouping(p) {
	case "stacked":
		if threeD {
			if col {
				return Col3DStacked
			}
			return Bar3DStacked
		}
		if col {
			return ColStacked
		}
		return BarStacked
	case "percentStacked":
		if threeD {
			if col {
				return Col3DPercentStacked
			}
			return Bar3DPercentStacked
		}
		if col {
			return ColPercentStacked
		}
		return BarPercentStacked
	default:
		if threeD {
			if col {
				return Col3DClustered
			}
			return Bar3DClustered
		}
		if col {
			return Col
		}
		return Bar
	}
}

// areaType resolves an area plot to a ChartType from its grouping. threeD
// selects the 3-D variants.
func areaType(p *decodeChartPlot, threeD bool) ChartType {
	switch chartGrouping(p) {
	case "stacked":
		if threeD {
			return Area3DStacked
		}
		return AreaStacked
	case "percentStacked":
		if threeD {
			return Area3DPercentStacked
		}
		return AreaPercentStacked
	default:
		if threeD {
			return Area3D
		}
		return Area
	}
}
