// Copyright 2016 - 2026 The excelize Authors. All rights reserved. Use of
// this source code is governed by a BSD-style license that can be found in
// the LICENSE file.
//
// Package excelize providing a set of functions that allow you to write to and
// read from XLAM / XLSM / XLSX / XLTM / XLTX files. Supports reading and
// writing spreadsheet documents generated by Microsoft Excel™ 2007 and later.
// Supports complex components by high compatibility, and provided streaming
// API for generating or reading data from a worksheet with huge amounts of
// data. This library needs Go version 1.25.0 or later.

package excelize

import "strings"

// GetDataValidationListItems resolves the selectable values of a list-type
// data validation into their string form. It expands both inline lists
// written by SetDropList (for example "East,West,North") and worksheet range
// sources written by SetSqrefDropList (for example Sheet1!$A$1:$A$3), reading
// the referenced cells to obtain their values.
//
// The sheet argument names the worksheet the validation belongs to; it is used
// to resolve range sources that carry no explicit sheet qualifier. The second
// return value reports whether dv is a list validation with resolvable items;
// it is false for non-list validations. Empty cells in a range source are
// skipped so the returned items mirror what the drop-down actually offers.
func (f *File) GetDataValidationListItems(sheet string, dv *DataValidation) ([]string, bool, error) {
	if dv == nil || dv.Type != "list" {
		return nil, false, nil
	}
	formula := strings.TrimSpace(dv.Formula1)
	if formula == "" {
		return nil, false, nil
	}
	// Inline list: a quoted, comma-separated literal.
	if strings.HasPrefix(formula, "\"") && strings.HasSuffix(formula, "\"") && len(formula) >= 2 {
		inner := formula[1 : len(formula)-1]
		var items []string
		for _, part := range strings.Split(inner, ",") {
			items = append(items, strings.TrimSpace(part))
		}
		return items, true, nil
	}
	// Range source: an optional 'Sheet'! qualifier followed by a range ref.
	srcSheet, ref := sheet, formula
	if idx := strings.LastIndex(formula, "!"); idx != -1 {
		srcSheet = strings.Trim(formula[:idx], "'")
		ref = formula[idx+1:]
	}
	ref = strings.ReplaceAll(ref, "$", "")
	return f.rangeCellValues(srcSheet, ref)
}

// rangeCellValues reads the non-empty cell values of a single-cell or
// rectangular range reference in row-major order.
func (f *File) rangeCellValues(sheet, ref string) ([]string, bool, error) {
	if !strings.Contains(ref, ":") {
		ref += ":" + ref
	}
	coordinates, err := rangeRefToCoordinates(ref)
	if err != nil {
		return nil, false, err
	}
	_ = sortCoordinates(coordinates)
	var items []string
	for row := coordinates[1]; row <= coordinates[3]; row++ {
		for col := coordinates[0]; col <= coordinates[2]; col++ {
			cell, err := CoordinatesToCellName(col, row)
			if err != nil {
				return nil, false, err
			}
			val, err := f.GetCellValue(sheet, cell)
			if err != nil {
				return nil, false, err
			}
			if val != "" {
				items = append(items, val)
			}
		}
	}
	return items, true, nil
}
